alertmanager:
  enabled: false

server:
  global:
    scrape_interval: 15s
  resources:
    requests:
      memory: "400Mi"
      cpu: "200m"
    limits:
      memory: "800Mi"
      cpu: "400m"
  extraScrapeConfigs: []
  persistentVolume:
    enabled: false

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
